servers:
    - filename: classroom_1.csv
      port: 5000
      slaveid: 1
      params:
        - registerAddress: 0
          registerType: 2
          byteSwap: false
          wordSwap: false
          valueType: uint16
    - filename: classroom_2.csv
      port: 5001
      slaveid: 1
      params:
        - registerAddress: 0
          registerType: 2
          byteSwap: false
          wordSwap: false
          valueType: uint16
    - filename: classroom_3.csv
      port: 5002
      slaveid: 1
      params:
        - registerAddress: 0
          registerType: 0
          byteSwap: false
          wordSwap: false
          valueType: bool
