servers:
    - filename: classroom_1.csv
      port: 5000
      slaveid: 1
    - filename: classroom_2.csv
      port: 5001
      slaveid: 1
    - filename: classroom_3.csv
      port: 5002
      slaveid: 1
