servers:
    - filename: classroom_1.csv
      port: 5000
      slaveid: 1
      params:
        - regaddress: 0
          regtype: holding
          byteswap: false
          valuetype: int16
    - filename: classroom_2.csv
      port: 5001
      slaveid: 1
      params:
        - regaddress: 0
          regtype: holding
          byteswap: false
          valuetype: int16
    - filename: classroom_3.csv
      port: 5002
      slaveid: 1
      params:
        - regaddress: 0
          regtype: coil
          byteswap: false
          valuetype: bool
