servers:
    - filename: classroom_1.csv
      port: 5000
      missingRate: 0
      timestep: 5
      params:
        - regaddress: 0
          regtype: holding
          byteswap: false
          valuetype: float32
    - filename: classroom_2.csv
      port: 5001
      missingRate: 0.3
      timestep: 5
      params:
        - regaddress: 0
          regtype: holding
          byteswap: false
          valuetype: int16
    - filename: classroom_3.csv
      port: 5002
      missingRate: 0.7
      timestep: 10
      params:
        - regaddress: 0
          regtype: coil
          byteswap: false
          valuetype: bool
    - filename: elec.csv
      port: 5003
      hasHeader: true
      hasIndex: true
      missingRate: 0.05
      timestep: 12
      params:
        - regaddress: 0
          regtype: holding
          byteswap: false
          valuetype: float32
        - regaddress: 2
          regtype: holding
          byteswap: false
          valuetype: float32
        - regaddress: 4
          regtype: holding
          byteswap: false
          valuetype: float32
        - regaddress: 6
          regtype: holding
          byteswap: false
          valuetype: float32
        - regaddress: 8
          regtype: holding
          byteswap: false
          valuetype: float32

